ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path('users/', include('users.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/store/urls.py
from django.urls import path
from . import views

urlpatterns = [

	#Leave as empty string for base url
	path('', views.store, name="store"),
	path('store/search', views.search, name="search"),
	path('store',views.store, name="store"),
	path('cart/', views.cart, name="cart"),
	path('checkout/', views.checkout, name="checkout"),
	path('product/<product_id>',views.product_details,name='product_details'),
	path('update_item/', views.updateItem, name="update_item"),
	path('review/<product_id>',views.reviewAdd,name="review"),
	path('process_order/', views.processOrder, name="process_order"),
	path('ajax/load-states/', views.load_states, name='ajax_load_states'), # AJAX

]

ecommerce/store/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Customer(models.Model):
	user = models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE)
	name = models.CharField(max_length=200, null=True)
	email = models.CharField(max_length=200)

	def __str__(self):
		return self.name



# Color
class Color(models.Model):
    title=models.CharField(max_length=100)

    class Meta:
        verbose_name_plural='Colors'

    def __str__(self):
        return self.title

# Size
class Size(models.Model):
    title=models.CharField(max_length=100)

    class Meta:
        verbose_name_plural='Sizes'

    def __str__(self):
        return self.title

class Product(models.Model):
	name = models.CharField(max_length=200)
	price = models.DecimalField(max_digits=7,decimal_places=2)
	digital = models.BooleanField(default=False,null=True, blank=True)
	image = models.ImageField(null=True, blank=True)
	description = models.TextField(null=True, blank=True)
	
	def __str__(self):
		return self.name

	@property
	def imageURL(self):
		try:
			url = self.image.url
		except:
			url = ''
		return url

# Product Attribute
class ProductAttribute(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    color=models.ForeignKey(Color,on_delete=models.CASCADE)
    size=models.ForeignKey(Size,on_delete=models.CASCADE)
   
    class Meta:
        verbose_name_plural='ProductAttributes'

    def __str__(self):
        return self.product.name

class Order(models.Model):
	customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True, blank=True)
	date_ordered = models.DateTimeField(auto_now_add=True)
	complete = models.BooleanField(default=False)
	transaction_id = models.CharField(max_length=100, null=True)

	@property
	def shipping(self):
		shipping = False
		orderitems = self.orderitem_set.all()
		for i in orderitems:
			if i.product.digital == False:
				shipping = True
		return shipping
	
	@property
	def get_cart_total(self):
		orderitems = self.orderitem_set.all()
		total = sum([item.get_total for item in orderitems])
		return total 

	@property
	def get_cart_items(self):
		#import pdb;
		#pdb.set_trace()
		orderitems = self.orderitem_set.all()
		total = sum([item.quantity for item in orderitems])
		return total 

	def __str__(self):
		return str(self.id)


class OrderItem(models.Model):
	product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
	order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)
	quantity = models.IntegerField(default=0, null=True, blank=True)
	date_added = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return str(self.product)
	
	@property
	def get_total(self):
		total = self.product.price * self.quantity
		return total


class Country(models.Model):
    name = models.CharField(max_length=50)
 
    def __str__(self):
        return self.name
   
class State(models.Model):
    country = models.ForeignKey(Country, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)
 
    def __str__(self):
        return self.name

class ShippingAddress(models.Model):
	customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True)
	order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)
	address = models.CharField(max_length=200, null=False)
	city = models.CharField(max_length=200, null=False)
	country = models.ForeignKey(Country, on_delete=models.SET_NULL, null=True)
	state = models.ForeignKey(State, on_delete=models.SET_NULL, null=True)
	zipcode = models.CharField(max_length=200, null=False)
	date_added = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.address

class ProductReview(models.Model):
	user=models.ForeignKey(User,on_delete=models.CASCADE)
	product=models.ForeignKey(Product,on_delete=models.CASCADE)
	comment=models.TextField(max_length=250)
	rating=models.FloatField(default=0)
	created_at=models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return str(self.product)

ecommerce/store/forms.py
from django import forms
from .models import ProductReview

# Review Add Form
class ReviewForm(forms.ModelForm):
	class Meta:
		model=ProductReview
		fields=['comment','rating']
		
		

ecommerce/store/views.py
from django.conf import settings
#from django.core.cache.backends.base import DEFAULT_TIMEOUT
#from django.views.decorators.cache import cache_page
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render
from django.http import JsonResponse
from store.forms import ReviewForm
from django.contrib import messages
from .models import *
from .utils import cookieCart,cartData, guestOrder
import datetime
import json


# Create your views here.
#CACHE_TTL = getattr(settings, 'CACHE_TTL', DEFAULT_TIMEOUT)

#@cache_page(CACHE_TTL)
def store(request):
	data = cartData(request)
	
	cartItems = data['cartItems']
	order = data['order']
	items = data['items']

	products = Product.objects.all()
	context = {'products':products, 'cartItems':cartItems}
	return render(request, 'store/store.html', context)

def cart(request):
	data = cartData(request)
	
	cartItems = data['cartItems']
	order = data['order']
	items = data['items']

	context = {'items':items, 'order':order, 'cartItems':cartItems}
	return render(request, 'store/cart.html', context)


#@login_required(login_url="../users/login")
def checkout(request):
	data = cartData(request)
	
	cartItems = data['cartItems']
	order = data['order']
	items = data['items']

	Countrys = Country.objects.all()
	context = {'items':items, 'order':order, 'cartItems':cartItems,'countrys':Countrys}
	return render(request, 'store/checkout.html', context)

def product_details(request,product_id):
	data = cartData(request)
	
	cartItems = data['cartItems']
	order = data['order']
	items = data['items']

	product_details = Product.objects.get(id=product_id)
	#colors=ProductAttribute.objects.filter(product=product_id).values('color__id','color__title').distinct()
	sizes = ProductAttribute.objects.filter(product=product_id).values('size__id','size__title').distinct()
	if request.user.is_authenticated:
		try:
			orderproduct = OrderItem.objects.filter(order__customer__user=request.user, product_id=product_id).exists()
		except Order.DoesNotExist:
			orderproduct = None
	else:
		orderproduct = None

	# Get the reviews
	reviews = ProductReview.objects.filter(product_id=product_id)

	context = {'product_details':product_details,'order':order, 'cartItems':cartItems,'reviews':reviews,'orderproduct':orderproduct,'sizes':sizes}
	return render(request, 'store/product_details.html',context)

def updateItem(request):
	data = json.loads(request.body)
	productId = data['productId']
	action = data['action']

	customer = request.user.customer
	product = Product.objects.get(id=productId)
	order, created = Order.objects.get_or_create(customer=customer, complete=False)
	#import pdb;
	#pdb.set_trace()
	orderItem, created = OrderItem.objects.get_or_create(order=order, product=product)

	if action == 'add':
		orderItem.quantity = (orderItem.quantity + 1)
	elif action == 'remove':
		orderItem.quantity = (orderItem.quantity - 1)

	orderItem.save()

	if orderItem.quantity <= 0:
		orderItem.delete()

	return JsonResponse('Item was added', safe=False)

def reviewAdd(request,product_id):
	url = request.META.get('HTTP_REFERER') 
	if request.method == 'POST':
		try:
			reviews = ProductReview.objects.get(user__id=request.user.id, product__id=product_id)
			form = ReviewForm(request.POST, instance=reviews)
			form.save()
			messages.success(request, 'Thank you! Your review has been.')
			return redirect(url)
		except ProductReview.DoesNotExist:
			form = ReviewForm(request.POST)
			if form.is_valid():
				data = ProductReview()
				data.rating = form.cleaned_data['rating']
				data.comment = form.cleaned_data['comment']
				data.product_id = product_id
				data.user_id = request.user.id
				data.save()
				messages.success(request, 'Thank you! Your review has been.')
				return redirect(url)

def search(request):
	q=request.GET['q']
	data=Product.objects.filter(name__icontains=q).order_by('-id')
	return render(request,'store/search.html',{'data':data})

def processOrder(request):
	transaction_id = datetime.datetime.now().timestamp()
	data = json.loads(request.body)

	if request.user.is_authenticated:
		customer = request.user.customer
		order, created = Order.objects.get_or_create(customer=customer, complete=False)
		
	else:
		customer,order = guestOrder(request, data)

	total = float(data['form']['total'])
	order.transaction_id = transaction_id

	if total == float(order.get_cart_total):
		order.complete = True
	order.save()

	if order.shipping == True:
		ShippingAddress.objects.create(
		customer=customer,
		order=order,
		address=data['shipping']['address'],
		city=data['shipping']['city'],
		state=State.objects.get(id=data['shipping']['state']),
		country=Country.objects.get(id=data['shipping']['country']),
		zipcode=data['shipping']['zipcode'],
		)

	return JsonResponse('Payment submitted..', safe=False)

# AJAX
def load_states(request):
	country_id = request.GET.get('country_id')
	states = State.objects.filter(country_id=country_id).all()
	return render(request, 'store/states_list.html', {'states': states})

ecommerce/store/templates/store/cart.html
{% extends 'store/main.html' %}
{% load static %}
{% block content %}
<div class="row">
    <div class="col-lg-12">
        <div class="box-element">

            <a  class="btn btn-outline-dark" href="{% url 'store' %}">&#x2190; Continue Shopping</a>

            <br>
            <br>
            <table class="table">
                <tr>
                    <th><h5>Items: <strong>{{order.get_cart_items}}</strong></h5></th>
                    <th><h5>Total: <strong>${{order.get_cart_total}}</strong></h5></th>
                    <th>
                        <a  style="float:right; margin:5px;" class="btn btn-success" href="{% url 'checkout' %}">Checkout</a>
                    </th>
                </tr>
            </table>

        </div>

        <br>
        <div class="box-element">
            <div class="cart-row">
                <div style="flex:2"></div>
                <div style="flex:2"><strong>Item</strong></div>
                <div style="flex:1"><strong>Price</strong></div>
                <div style="flex:1"><strong>Quantity</strong></div>
                <div style="flex:1"><strong>Total</strong></div>
            </div>
            
            
                {% for item in items %}

				<div class="cart-row">
					<div style="flex:2"><img class="row-image" src="{{item.product.imageURL}}"></div>
					<div style="flex:2"><p>{{item.product.name}}</p></div>
					<div style="flex:1"><p>${{item.product.price}}</p></div>
					<div style="flex:1">
						<p class="quantity">{{item.quantity}}</p>
						<div class="quantity">
							<img data-product="{{item.product.id}}" data-action="add" class="chg-quantity update-cart" src="{% static  'images/arrow-up.png' %}">
					
							<img data-product="{{item.product.id}}" data-action="remove" class="chg-quantity update-cart" class="chg-quantity" src="{% static  'images/arrow-down.png' %}">
						</div>
					</div>
					<div style="flex:1"><p>${{item.get_total}}</p></div>
				</div>
				{% endfor %}
            </div>

        </div>
    </div>
</div>
{% endblock content %}

ecommerce/store/templates/store/checkout.html
{% extends 'store/main.html' %} {% load static %} {% block content %}
<div class="row">
  <div class="col-lg-6">
    <div class="box-element" id="form-wrapper">
      <form
        id="form"
        method="post"
        data-states-url="{% url 'ajax_load_states' %}"
      >
        <div id="user-info">
          <div class="form-field">
            <input
              required
              class="form-control"
              type="text"
              name="name"
              placeholder="Name.."
            />
          </div>
          <div class="form-field">
            <input
              required
              class="form-control"
              type="email"
              name="email"
              placeholder="Email.."
            />
          </div>
        </div>

        <div id="shipping-info">
          <hr />
          <p>Shipping Information:</p>
          <hr />
          <div class="form-field">
            <input
              class="form-control"
              type="text"
              name="address"
              placeholder="Address.."
            />
          </div>
          <div class="form-field">
            <select name="country" class="form-control" id="id_country">
              {% for country in countrys %}
              <option value="{{ country.pk }}">{{ country.name }}</option>
              {% endfor %}
            </select>
          </div>
          <div class="form-field">
            <input
              class="form-control"
              type="text"
              name="city"
              placeholder="City.."
            />
          </div>
          <div class="form-field">
            <select name="state" class="form-control" id="id_state">
              <option value=""></option>
            </select>
          </div>
          <div class="form-field">
            <input
              class="form-control"
              type="text"
              name="zipcode"
              placeholder="Zip code.."
            />
          </div>
        </div>

        <hr />
        <input
          id="form-button"
          class="btn btn-success btn-block"
          type="submit"
          value="Continue"
        />
      </form>
    </div>

    <br />
    <div class="box-element hidden" id="payment-info">
      <small>Paypal Options</small>
      <button id="make-payment">Make payment</button>
    </div>
  </div>

  <div class="col-lg-6">
    <div class="box-element">
      <a class="btn btn-outline-dark" href="{% url 'cart' %}"
        >&#x2190; Back to Cart</a
      >
      <hr />
      <h3>Order Summary</h3>
      <hr />
      {% for item in items %}
      <div class="cart-row">
        <div style="flex: 2">
          <img class="row-image" src="{{item.product.imageURL}}" />
        </div>
        <div style="flex: 2"><p>{{item.product.name}}</p></div>
        <div style="flex: 1"><p>${{item.product.price|floatformat:2}}</p></div>
        <div style="flex: 1"><p>x{{item.quantity}}</p></div>
      </div>
      {% endfor %}
      <h5>Items: {{order.get_cart_items}}</h5>
      <h5>Total: ${{order.get_cart_total|floatformat:2}}</h5>
    </div>
  </div>
</div>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script type="text/javascript">
  $("#id_country").change(function () {
    const url = $("#form").attr("data-states-url"); // get the url of the `load_states` view
    const countryId = $(this).val(); // get the selected country ID from the HTML input

    $.ajax({
      // initialize an AJAX request
      url: url, // set the url of the request (= /store/ajax/load-states/ )
      data: {
        country_id: countryId, // add the country id to the GET parameters
      },
      success: function (data) {
        // `data` is the return of the `load_states` view function
        $("#id_state").html(data); // replace the contents of the state input with the data that came from the server
      },
    });
  });

  var shipping = "{{order.shipping}}";
  var total = "{{order.get_cart_total|floatformat:2}}";

  if (shipping == "False") {
    document.getElementById("shipping-info").innerHTML = "";
  }

  if (user != "AnonymousUser") {
    document.getElementById("user-info").innerHTML = "";
  }

  if (shipping == "False" && user != "AnonymousUser") {
    //Hide entire form if user is logged in and shipping is false
    document.getElementById("form-wrapper").classList.add("hidden");
    //Show payment if logged in user wants to buy an item that does not require shipping
    document.getElementById("payment-info").classList.remove("hidden");
  }

  var form = document.getElementById("form");
  form.addEventListener("submit", function (e) {
    e.preventDefault();
    console.log("Form Submitted...");
    document.getElementById("form-button").classList.add("hidden");
    document.getElementById("payment-info").classList.remove("hidden");
  });

  document
    .getElementById("make-payment")
    .addEventListener("click", function (e) {
      submitFormData();
    });

  function submitFormData() {
    console.log("Payment button clicked");

    var userFormData = {
      name: null,
      email: null,
      total: total,
    };

    var shippingInfo = {
      address: null,
      city: null,
      state: null,
      zipcode: null,
    };

    if (shipping != "False") {
      shippingInfo.address = form.address.value;
      shippingInfo.city = form.city.value;
      shippingInfo.state = form.state.value;
      shippingInfo.country = form.country.value;
      shippingInfo.zipcode = form.zipcode.value;
    }

    if (user == "AnonymousUser") {
      userFormData.name = form.name.value;
      userFormData.email = form.email.value;
    }

    console.log("Shipping Info:", shippingInfo);
    console.log("User Info:", userFormData);

    var url = "/process_order/";
    fetch(url, {
      method: "POST",
      headers: { "Content-Type": "application/json", "X-CSRFToken": csrftoken },
      body: JSON.stringify({
        form: userFormData,
        shipping: shippingInfo,
      }),
    }).then((response) => {
      console.log("Success:");
      alert("Txn Completed");
      window.location.href = "{% url 'store' %}";
    });
  }
</script>
{% endblock content %}

ecommerce/store/templates/store/main.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <title>MySite</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}" />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'css/custom.css' %}"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
    />

    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1"
    />

    <script type="text/javascript">
      var user = "{{request.user}}";

      function getToken(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie !== "") {
          var cookies = document.cookie.split(";");
          for (var i = 0; i < cookies.length; i++) {
            var cookie = cookies[i].trim();
            // Does this cookie string begin with the name we want?
            if (cookie.substring(0, name.length + 1) === name + "=") {
              cookieValue = decodeURIComponent(
                cookie.substring(name.length + 1)
              );
              break;
            }
          }
        }
        return cookieValue;
      }
      var csrftoken = getToken("csrftoken");
    </script>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="{% url 'store' %}">MyPaintingShop</a>
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'store' %}"
              >Store <span class="sr-only">(current)</span></a
            >
          </li>
        </ul>
        <div>
          <form
            class="form-inline my-2 my-lg-0"
            method="GET"
            action="{%url 'search' %}"
          >
            <input
              name="q"
              class="form-control mr-sm-2"
              type="text"
              placeholder="Search"
              aria-label="Search"
            />
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">
              Search
            </button>
          </form>
        </div>
        <div class="form-inline my-2 my-lg-0">
          {% if user.is_authenticated %}
          <span id="hello-msg"> Hello, {{ request.user }}</span>
          <a href="{% url 'logout' %}" class="btn btn-warning">Logout</a>

          {% else %}
          <a href="{% url 'login' %}" class="btn btn-warning">Login</a>
          {% endif %}
          <a href="{% url 'cart' %}">
            <img id="cart-icon" src="{% static 'images/cart.png' %}" />
          </a>
          <p id="cart-total">{{ cartItems }}</p>
        </div>
      </div>
    </nav>

    <div class="container">
      <br />
      {% block content %} {% endblock content %}
    </div>

    <!--<script
      src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
      integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
      crossorigin="anonymous"
    ></script>-->

    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
      integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
      crossorigin="anonymous"
    ></script>

    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
      integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
      crossorigin="anonymous"
    ></script>
    <script type="text/javascript" src="{% static 'js/cart.js' %}"></script>
  </body>
</html>

ecommerce/store/templates/store/product_details.html
{% extends 'store/main.html' %} {% load static %} {% block content %}
<div class="row">
  <div class="col-lg-12">
    <div class="box-element">
      <a class="btn btn-outline-dark" href="{% url 'store' %}"
        >&#x2190; Continue Shopping</a
      >

      <br />
    </div>
  </div>
</div>
<div class="cart-row">
  <div style="flex: 2">
    <img src="{{product_details.imageURL}}" />
  </div>
  <div class="col-md">
    <div class="card card-body">
      <h5>{{product_details.name}}</h5>
      <hr />
      <p>{{product_details.name}}</p>
      <p>Price:${{product_details.price}}</p>
      <hr />
      <h6>About Item:</h6>
      <p>{{product_details.description}}</p>

      {% if sizes %}
        <p>Size:</p>
        <p>
        <select name="size">
          {% for size in sizes %}
          <option value="{{ size.size__id }}">{{ size.size__title }}</option>
          {% endfor %}
        </select> 
      </p>
        {% endif %}
      <p>
        <button
          data-product="{{ product_details.id }}"
          data-action="add"
          class="btn btn-outline-secondary add-btn update-cart"
        >
          Add to Cart
        </button>
      </form>
      </p>
    </div>
    <div>
      <br />

      <h4>Customer Reviews</h4>
      <form method="POST" action="{%url 'review' product_details.id %}">
        {% csrf_token %}

        <!--Rating stars-->
        <label>How do you rate this product?</label><br />
        <div class="rate">
          <input
            type="radio"
            name="rating"
            id="rating10"
            value="5"
            required
          /><label for="rating10" title="5"></label>
          <input
            type="radio"
            name="rating"
            id="rating9"
            value="4.5"
            required
          /><label for="rating9" title="4.5" class="half"></label>
          <input
            type="radio"
            name="rating"
            id="rating8"
            value="4"
            required
          /><label for="rating8" title="4"></label>
          <input
            type="radio"
            name="rating"
            id="rating7"
            value="3.5"
            required
          /><label for="rating7" title="3.5" class="half"></label>
          <input
            type="radio"
            name="rating"
            id="rating6"
            value="3"
            required
          /><label for="rating6" title="3"></label>
          <input
            type="radio"
            name="rating"
            id="rating5"
            value="2.5"
            required
          /><label for="rating5" title="2.5" class="half"></label>
          <input
            type="radio"
            name="rating"
            id="rating4"
            value="2"
            required
          /><label for="rating4" title="2"></label>
          <input
            type="radio"
            name="rating"
            id="rating3"
            value="1.5"
            required
          /><label for="rating3" title="1.5" class="half"></label>
          <input
            type="radio"
            name="rating"
            id="rating2"
            value="1"
            required
          /><label for="rating2" title="1"></label>
          <input
            type="radio"
            name="rating"
            id="rating1"
            value="0.5"
            required
          /><label for="rating1" title="0.5" class="half"></label>
        </div>
        <p>Post your comment here</p>
        <textarea name="comment" rows="4" class="form-control"></textarea>
        <br />


        {% if user.is_authenticated %}
        {% if orderproduct %}
          <input type="submit" value="Submit Review" class="btn btn-primary">
        {% else %}
          <p>You must purchase this product to post a review.</p>
        {% endif %}
      {% else %}
      <p>You must be logged in to post a review. <span><a href="{% url 'login' %}">Login now</a></span></p>
      {% endif %}


        {% if messages %}

    {% for message in messages %}
    <div id="message" class="container">
    <div {% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %} role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span></button>
        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Error: {% endif %}
        {{ message }}
    </div>
    </div>
    {% endfor %}

{% endif %}
      </form>
    </div>
  <div>
    <br>
    <header class="section-heading">
      <h4>Customer Reviews </h4>
    </header>

    {% for review in reviews %}
           <article class="box mb-3">
              <div class="icontext w-100">
    
                <div class="text">
                  <span class="date text-muted float-md-right">{{review.created_at}} </span>
                  <h6 class="mb-1">{{review.user}} </h6>
                  <div class="rating-star">
                    <span>
                      <i class="fa fa-star{% if review.rating == 0.5 %}-half-o{% elif review.rating < 1 %}-o {% endif %}" aria-hidden="true"></i>
                      <i class="fa fa-star{% if review.rating == 1.5 %}-half-o{% elif review.rating < 2 %}-o {% endif %}" aria-hidden="true"></i>
                      <i class="fa fa-star{% if review.rating == 2.5 %}-half-o{% elif review.rating < 3 %}-o {% endif %}" aria-hidden="true"></i>
                      <i class="fa fa-star{% if review.rating == 3.5 %}-half-o{% elif review.rating < 4 %}-o {% endif %}" aria-hidden="true"></i>
                      <i class="fa fa-star{% if review.rating == 4.5 %}-half-o{% elif review.rating < 5 %}-o {% endif %}" aria-hidden="true"></i>
                    </span>
                  </div>
                </div>
              </div>
              <div class="mt-3">
              <p>
                  {{ review.comment }}
                </p>
              </div>
            </article>
    {% endfor %}
  </div>
  
  </div>
</div>
{% endblock content %}

ecommerce/store/templates/store/search.html
{% extends 'store/main.html' %} 
{% load static %} 
{% block content %}
<div class="row">
  <div class="col-lg-12">
    <div class="box-element">
      <a class="btn btn-outline-dark" href="{% url 'store' %}"
        >&#x2190; Continue Shopping</a>

      <br />
    </div>
  </div>
</div>
<div class="row">
    {% if data %}
    {% for product in data %}
    <div class="col-lg-4">
        <a href="{% url 'product_details' product.id %}"><img class="thumbnail" src="{{product.imageURL}}"></a>
        <div class="box-element product">
            <h6><strong>{{product.name}}</strong></h6>
            <h4 style="display: inline-block; float: right"><strong>${{product.price}}</strong></h4>
        </div>
    </div>
    {% endfor %}
    {% else %}
    <div class="col-lg-4"><h4>No results found!</h4>
    </div>
    {% endif %}
</div>
{% endblock content %}

ecommerce/store/templates/store/states_list.html
{% for state in states %}
<option value="{{ state.pk }}">{{ state.name }}</option>
{% endfor %}

ecommerce/store/templates/store/store.html
{% extends 'store/main.html' %}
{% load static %}
{% block content %}

<div class="row">
    {% for product in products %}
    <div class="col-lg-4">
        <a href="{% url 'product_details' product.id %}"><img class="thumbnail" src="{{product.imageURL}}"></a>
        <div class="box-element product">
            <h6><strong>{{product.name}}</strong></h6>
            <hr>

            <button data-product="{{ product.id }}" data-action="add" class="btn btn-outline-secondary add-btn update-cart">Add to Cart</button>
           <!-- <a class="btn btn-outline-success" href="#">View</a>-->
            <h4 style="display: inline-block; float: right"><strong>${{product.price}}</strong></h4>

        </div>
    </div>
    {% endfor %}
</div>




{% endblock content %}